spring:
  profile: test
  name: Test-Yml
  environment: test
  servers:
    -ip: 127.0.0.1
    port: 8888

  email: chandan.singh116@gmail.com

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useSSL=false
    username: root
    password: root

  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy